### ISSUE TITLE
Fix all the broken unit tests

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#131]
Related Issues:
- [x] #61 - Commented out tests
- [ ] #75 - Example: `SDLAddCommandSpec` - [Getter/Setter Tests / Should return nil if not set]
- [x] #79 - `SDLRPCRequestFactorySpec` - [BuildPerformAudioPassThru Tests / Should build correctly] - PR #138 
- [x] #80 - `SDLRPCRequestFactorySpec` - Crash - PR #133 
- [x] #82 - `SDLRPCMessageTypeSpec` - All failures - PR #141 
- [x] #83 - `SDLOnLockScreenStatusSpec` - [Getter/Setter Tests / Should set and get correctly] - PR #135 
- [x] #84 - `SDLV1ProtocolHeaderSpec` - [Data Tests / Should convert to byte data correctly] - PR #134 
- [x] #90 - `SDLProtocolSpec` - [SendEndSession Tests / During V1 Session / Should send the correct data] - PR #136 
- [x] #92 - `SDLProtcolAssemblerSpec` - Lines 86-93 - PR #138 
- [x] #95 - `SDLFunctionIDSpec` - [GetFunctionName Tests / Should return the correct function name]
- [x] #132 - `SDLV1ProtocolHeaderSpec` - [Copy Tests / Should copy correctly] - PR #137 
- [x] #143 - `SDLPrioritizedObjectCollectionSpec` - [a prioritized object collection / should retrieve higher priority objects first]
