### ISSUE TITLE
4.0 RPC updates

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#146]
The following enums need to be updated to match the latest version of the 4.0 mobile api spec:

~~LayoutMode~~
~~AppInterfaceUnregisteredReason~~
~~AmbientLightStatus~~
- [x] TextFieldName - PR #158
- [x] ImageFieldName - PR #159 
- [x] VehicleDataResultCode - PR #165
- [x] KeyboardEvent - PR #160
- [x] RequestType - PR #163
- [x] Result - PR #164

The following classes need to be updated to match the latest version of the 4.0 mobile api spec:

- [x] TouchEvent - PR #154, may need revision
- [x] HMICapabilities (new) - PR #157 
- [x] FunctionID - Respective PRs
- [x] RegisterAppInterface (response) (see issue #178)
- [x] PutFile (request) - PR #166
- [x] DialNumber (new - request, response) - PR #153 
- [x] OnSystemRequest (notification) - May need revision according to internal discussion
- [x] SendLocation (request / response) - PR #167 
- [x] ChangeRegistration - PR #273 

- [ ] PR #287 

App Launching needs to support `VRSynonyms` and `TTSName`.

Stolen from https://github.com/smartdevicelink/sdl_android/issues/150

**Comment by stefanek22** [comment]
Is the DialNumber API included?

**Comment by joeljfischer** [comment]
I haven't heard of a DialNumber API. I'm still trying to figure out what I need to know here. The only "4.0" feature that I know about and have implemented is App Querying and Launching.

**Comment by justinjdickow** [comment]
Are we also supposed to consider the lock screen icon url part of 4.0? The RequestType is in the spec, and I can merge that code into core if needed

**Comment by stefanek22** [comment]
@joeljfischer DialNumber is one of the targeted APIs for v4.0 (a relatively simple request from an app to initiate a phone call from the connected device).  It was included to combat (currently iOS only) restrictions on when a phone call could be placed (e.g. not possible when app is in background and phone is locked).

@justinjdickow Our understanding was that the lockscreen feature would also be included in the v4.0 release.  Is this containable?

**Comment by joeljfischer** [comment]
@stefanek22 It looks like there's also a new `SendLocation` request & response. I'm assuming that was overlooked and should be included?

**Comment by stefanek22** [comment]
Correct.  It was actually part of the v3.1 feature set before.  But this alignment is only now occurring.  It needs to be included.

**Comment by joeljfischer** [comment]
Cool. Anything else that we may have missed that I should look for?

**Comment by stefanek22** [comment]
There does not appear to be anything else.  If anyone has identified anything, please let us know.

**Comment by joeljfischer** [comment]
@stefanek22 

1. The `AppInterfaceUnregistered` enum seems to have a value of `PROTOCOL_VIOLATION` that is not implemented in the library

1. The `ImageFieldName` enum has an unimplemented value of `locationImage`

1. The `Result` enum used to have a `CHAR_LIMIT_EXCEEDED` value that is not present in the 4.0 spec I have, and it appears it was never implemented. That value does still appear in the `resultCode` of `ScrollableMessage`, however.

Any thoughts on these?

**Comment by stefanek22** [comment]
1)  PROTOCOL_VIOLATION was defined prior to protect for such a scenario (protocol layer violation which qualifies for an app to be unregistered).  Though it is not implemented, it should cause harm by remaining in the enum list.
2)  locationImage should be part of the SendLocation RPC.  It is the sole image that can be sent with the location metadata.
3)  CHAR_LIMIT_EXCEEDED was supposed to be a warning result that still returned successful.  It should have been implemented;  the enum should be added to Result regardless if it exists anywhere else.

**Comment by joeljfischer** [comment]
> Though it is not implemented, it should cause harm by remaining in the enum list.

I'm not sure what you mean by this

> locationImage should be part of the SendLocation RPC

Yeah, I added this in there. This is something else I think though, as it's part of the `ImageFieldName` enum. Was it an error to be added there?

> It should have been implemented; the enum should be added to Result regardless if it exists anywhere else.

It was there previously, and must have been removed from the 4.0 spec. Should it be added back in to the `Result` enum in the spec?

**Comment by stefanek22** [comment]
1)  Meant to say that this enum definition can remain (with the intention that it is implemented at some point in the near future) without having to remove it.
2)  No, it was not an error.  All image fields need to be defined in ImageFieldName as their image types and resolution are then properly broadcast during registration, etc.
3)  Correct, the spec should have it added back.

**Comment by idamaster** [comment]
Similar to what's happening with https://github.com/smartdevicelink/sdl_android/pull/153 can we take a look at timing/updates for this particular issue? Can we do a WIP PR and start to drive to closure?

**Comment by joeljfischer** [comment]
@idamaster I definitely want to drive to closure here and get the release train going for 4.0.

There are 2 remaining issues as I see them.

1. Issue #178, I'm pretty suspicious about the `systemSoftwareVersion` and `sdlVersion` parameters, and it sounds like it might end up being something that needs careful discussion and discovery. I would propose that we hold off on those two parameters until a later minor release rather than get something in, only to have to remove it in a major release to get the 'correct' api in.

1. We've been trying to get clarification around the new 'long' types as seen in OnSystemRequest. Core was not at all prepared for these changes, and I believe @justinjdickow mentioned there were crashes. We need more discussion about these changes and what they mean for version numbers. That is, does changing something to a `Long` mean that it's a major version change, as you're effectively removing the old api to replace it with something else. Is there anything more on Core that needs to be done. Additional types were changed to 'Long' elsewhere, as well.

**Comment by joeljfischer** [comment]
Every pull request has been created for this

**Comment by Heath-FoMoCo** [comment]
Can you link the pull request(s) for this issue?  I have not been able to find it.

**Comment by justinjdickow** [comment]
@joeljfischer please see heath's question

**Comment by justinjdickow** [comment]
@adein 

Will also be adding a pull request for ShowConstantTBT, UpdateTurnList, AlertManeuver

**Comment by joeljfischer** [comment]
* `DeviceInfo` is correct
* `ChangeRegistration` exists but doesn't contain all of the parameters
* `ShowConstantTBT` is correct
* `UpdateTurnList` is correct
* `AlertManeuver` is correct

Based on [this RPC spec](https://github.com/smartdevicelink/rpc_spec/blob/master/spec.xml)

**Comment by adein** [comment]
@joeljfischer The last 3 are just missing from the factory.
